version: "3"
services:
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
      - mailhog
    image: wordpress:latest
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: "
      \ndefine('WP_SITEURL', 'http://' . $$_SERVER['HTTP_HOST']);
      \ndefine('WP_HOME', 'http://' . $$_SERVER['HTTP_HOST']);
      "
    volumes:
      - ./src:/var/www/html/wp-content/themes/${THEME_SLUG}
      - wp:/var/www/html

  cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    volumes:
      - wp:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: wordpress
      MYSQL_ROOT_PASSWORD: wordpress

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8282:8025

volumes:
  db_data:
  wp:
